### ISSUE TITLE
Consider relaxing `non_exhaustive` use across the crate

### ISSUE THREAD

**Issue by sanbox-irl** [SecondHalfGames/yakui#196]
There are a significant number of structs, especially utilities, which have `non-exhaustive` placed on them, such as `Align`. I understand that non_exhaustive can be used to make all fields of a struct public which making it a semver hazard, but the library is still pre-1.0, and has no such semver promises. (remembering `Rect::from_pos_size` vs. just writing it out keeps getting me).

Is there any interest in a PR that would relax many of these restrictions?

**Comment by Ralith** [comment]
My experience of `#[non_exhaustive]` on a public API is that usually you end up needing to break semver anyway because you want to remove a field or change a type. If you really want to be semver-robust, then private fields with public setters are much better at keeping your options open, but also avoiding actual code churn is probably much more important than technical semver breaks, and even that isn't too important when the whole project's unstable.

**Comment by sanbox-irl** [comment]
Yeah that tends to be my feeling. I think API churn is fine especially in a library this young and this particular

**Comment by LPGhatguy** [comment]
I'm game for this

**Comment by sanbox-irl** [comment]
Made a PR, #197

**Comment by LPGhatguy** [comment]
Closed by #197.

**Comment by sanbox-irl** [comment]
thanks ya'll!
